user/urls.py
from django.contrib import admin
from django.urls import path
from user.views import *

app_name = "user"

urlpatterns = [
	path("register/", register, name = "register"),
	path("login/", loginUser, name = "login"),
	path("dashboard/", dashboard, name = "dashboard"),
	path("logout/", logoutUser, name = "logout"),
	path("addarticle/", addarticle, name = "addarticle"),
	path("detail/<int:id>", detail, name = "detail"),
	path("update/<int:id>", updateArticle, name = "update"),
	path("delete/<int:id>", deleteArticle, name = "delete")
]

zz/urls.py
from django.contrib import admin
from django.urls import path, include
from article.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name = "index"),
    path("about/", about, name = "about"),
    path("article/", article, name = "article"),
    path("user/", include("user.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):

	author = models.ForeignKey("auth.User", on_delete = models.CASCADE, verbose_name = "Yazar")
	title = models.CharField(max_length = 50 , verbose_name = "Başlık")
	content = RichTextField(verbose_name = "İçerik")
	date = models.DateTimeField(auto_now_add = True, verbose_name = "Oluşturulma Tarihi")
	article_image = models.FileField(blank = True, null = True, verbose_name = "Yazı ile ilgli bir görsel ekleyebilirsiniz")

	def __str__(self):
		return self.title

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.forms import ModelForm
from article.models import Article

class RegisterForm(forms.Form):

	username = forms.CharField(max_length = 50, label = "Kullanıcı Adı")
	password = forms.CharField(max_length = 50, label = "Şifre", widget = forms.PasswordInput)
	confirm = forms.CharField(max_length = 50, label = "Şifre (tekrar)", widget = forms.PasswordInput)

	def clean(self):

		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")
		confirm = self.cleaned_data.get("confirm")

		if password and confirm and password != confirm:
			raise forms.ValidationError("Şifreler Eşleşmiyor")

		values = {
			"username" : username,
			"password" : password,
			"confirm" : confirm
		}

		return values

class LoginForm(forms.Form):

	username = forms.CharField(max_length = 50, label = "Kullanıcı Adı")
	password = forms.CharField(max_length = 50, label = "Şifre", widget = forms.PasswordInput)

class ArticleForm(ModelForm):

	class Meta:
		model = Article
		fields = ["title", "content", "article_image"]

article/views.py
from django.shortcuts import render
from article.models import Article

# Create your views here.
def index(request):
	return render(request, "index.html")

def about(request):
	return render(request, "about.html")

def article(request):

	keyword = request.GET.get("keyword")

	if keyword:
		articles = Article.objects.filter(title__contains = keyword)
		return render(request, "article.html",{"articles":articles})

	articles = Article.objects.all()
	return render(request, "article.html",{"articles":articles})

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from user.forms import RegisterForm, LoginForm, ArticleForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from article.models import Article
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):

	form = RegisterForm(request.POST or None)
	context = {"form":form}

	if form.is_valid():

		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")

		newUser = User(username = username)
		newUser.set_password(password)
		newUser.save()

		login(request, newUser)
		messages.success(request, "Kayıt Alındı ve Giriş Yapıldı")
		return redirect("index")

	return render(request, "register.html", context)

def loginUser(request):

	form = LoginForm(request.POST or None)
	context = {"form":form}

	if form.is_valid():
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")

		user = authenticate(username = username, password = password)

		if user is None:
			messages.warning(request, "Kullanıcı Adı veya Şifre Hatalı")
			return render(request, "login.html", context)

		user.save()
		login(request, user)
		messages.success(request, "Giriş Başarılı")
		return redirect("index")
		
	return render(request, "login.html", context)

@login_required(login_url  = "user:login")
def dashboard(request):

	articles = Article.objects.filter(author = request.user)
	return render(request, "dashboard.html",{"articles":articles})

def logoutUser(request):
	logout(request)
	messages.warning(request, "Çıkış Yapıldı")
	return redirect("index")

@login_required(login_url  = "user:login")
def addarticle(request):

	form = ArticleForm(request.POST or None, request.FILES or None)
	context = {"form":form}

	if form.is_valid():

		article = form.save(commit = False)
		article.author = request.user
		article.save()

		messages.success(request, "Yazı Eklendi")
		return redirect("user:dashboard")
	return render(request, "addarticle.html", context)

def detail(request,id):
	
	#article = Article.objects.filter(id=id).first()
	article = get_object_or_404(Article,id=id)
	return render(request, "detail.html",{"article":article})

@login_required(login_url  = "user:login")
def updateArticle(request,id):

	article = get_object_or_404(Article, id = id)
	form = ArticleForm(request.POST or None, request.FILES or None, instance = article)

	if form.is_valid():
		article = form.save(commit = False)
		article.author = request.user
		article.save()

		messages.success(request, "Yazı Güncellendi")
		return redirect("index")

	return render(request,"update.html",{"form":form})

@login_required(login_url  = "user:login")
def deleteArticle(request, id):

	article = get_object_or_404(Article, id = id)
	article.delete()
	messages.success(request, "Yazı Silindi")
	return redirect("user:dashboard")

templates/about.html
{% extends "layout.html" %}

{% block body %}

	<div class="jumbotron text-center">
		<h3>Ben UTKU</h3>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam nemo, dicta maiores deleniti iste itaque laborum facere quam, ipsum delectus excepturi. Eius sunt quod, dolores ipsum nulla voluptate blanditiis quaerat facere earum voluptas minima porro amet aspernatur quam qui, ullam quia! Expedita blanditiis, aliquid modi ad saepe dolorem beatae quia perspiciatis eum corporis, non sint fugiat esse, consequuntur ratione deserunt reiciendis, ullam quod sunt. Sapiente explicabo qui sunt modi aliquid ullam eaque blanditiis ipsa esse inventore quas illum, magnam cumque voluptatibus a minus? Libero odit nesciunt, fuga culpa non perferendis asperiores itaque earum unde dicta natus ad dignissimos expedita consequatur!
		</p>
	</div>
    
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
	
	<div class = "mx-auto" style = "width : 75%;">
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{form|crispy}}
			{{form.media}}
			<button class = "btn btn-info" type = "submit">Gönder</button>
		</form>
	</div>
    
{% endblock body %}

templates/article.html
{% extends "layout.html" %}
{% block body %}
	<h3>Yazılar</h3>
	<hr>
		<form class="form-inline">
			{% csrf_token %}
			<input class="form-control mr-sm-2" type="text" name="keyword" placeholder="Ara" aria-label="Search">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Başlıkta Ara</button>
		</form>
	{% if articles %}
		{% for article in articles %}
			<div class="row" style = "margin-bottom: 50px;">
				<!-- Post Content Column -->
				<div class="col-lg-8">
					<!-- Title -->
					<h1 class="mt-4">{{article.title}}</h1>
					<!-- Author -->
					<p class="lead">
						{{article.author}}
					</p>
					<!-- Date/Time -->
					<p>{{article.date}}</p>
					<hr>
					<!-- Preview Image -->
					{% if article.article_image %}
						<img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
						<hr>
						test
					{% endif %}
					<!-- Post Content -->
					<p class="lead">{{article.content|safe|truncatewords:10}}</p>
					<a href="/user/detail/{{article.id}}" class = "alert alert-info">Devamını Oku</a>
					
					
				</div>
			</div>
		{% endfor %}
	{% else %}
		<div class = "alert alert-danger">Herhangi bir yazı bulunmuyor.</div>
		
		
	{% endif %}
	
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

	<h3>Panel</h3>
	<hr>
	{% if request.user.is_authenticated %}
	<p>merhaba, <small>{{request.user.username}}</small></p>
	{% endif %}
	<a href="{% url 'user:addarticle' %}" class = "btn btn-info">Yazı Ekle</a>
	<hr>
	{% if articles %}
	<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Oluşturulma Tarihi</th>
      <th scope="col">Güncelle / Sil</th>
    </tr>
  </thead>
  <tbody>
      {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="/user/detail/{{article.id}}">{{article.title}}</a></td>
      <td>{{article.author}}</td>
      <td>{{article.date}}</td>
      <td scope="col"><a style = "margin-right: 5px;" class = "btn btn-info" href="/user/update/{{article.id}}">Güncelle</a><a  class = "btn btn-warning"href="/user/delete/{{article.id}}">Sil</a><td>
    </tr>
      {% endfor %}
  </tbody>
</table>
{% else %}
    <div class = "alert alert-warning">Henüz Bir Yazınız Bulunmuyor</div>
	    
	
	{% endif %}
    
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-8">
      <!-- Title -->
      <h1 class="mt-4">{{article.title}}</h1>
      <!-- Author -->
      <p class="lead">
        {{article.author}}
      </p>
      <!-- Date/Time -->
      <p>{{article.date}}</p>
      <hr>
      <!-- Preview Image -->
      {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        <hr>
      {% endif %}
      <!-- Post Content -->
      <p class="lead">{{article.content|safe}}</p>
         
      
    </div>
  </div>
  <!-- /.row -->
{% endblock body %}

templates/includes/detail_source.html
<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Post Title</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2019 at 12:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

        <blockquote class="blockquote">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <footer class="blockquote-footer">Someone famous in
            <cite title="Source Title">Source Title</cite>
          </footer>
        </blockquote>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">UNT Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">

    <!-- left side -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'about' %}">Hakkımda</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article' %}">Yazılar</a>
      </li>
    </ul>

    <!-- left side -->
    <ul class="navbar-nav ml-auto">

      {% if request.user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:dashboard' %}">Panel</a>
      </li><li class="nav-item active">
        <a class="nav-link" href="{% url 'user:logout' %}">Çıkış</a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:register' %}">Kayıt</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:login' %}">Giriş</a>
      </li>
      {% endif %}
    </ul>

  </div>
</nav>

templates/index.html
{% extends "layout.html" %}

{% block body %}

	<div class="jumbotron text-center">
		<h3>Merhaba</h3>
		<p>
			Yazılım ile ilgli yazılarınızı bu blogda paylaşabilirsiniz.
		</p>
	</div>
    
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<title>UNT Blog</title>
	</head>
	<body>
		{% include "includes/navbar.html" %}
		<div class = "container" style = "margin-top : 20px;">
			{% if messages %}
				<ul class="messages">
					{% for message in messages %}
						<div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
					{% endfor %}
				</ul>
			{% endif %}
			{% block body %}
				
			{% endblock body %}
		</div>
	

	<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
	
	</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
	
	<div class = "mx-auto" style = "width : 50%;">
		<form method="post">
			{% csrf_token %}
			{{form|crispy}}
			<button class = "btn btn-info" type = "submit">Kayıt</button>
		</form>
	</div>
    
{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
	
	<div class = "mx-auto" style = "width : 50%;">
		<form method="post">
			{% csrf_token %}
			{{form|crispy}}
			<button class = "btn btn-info" type = "submit">Kayıt</button>
		</form>
	</div>
    
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
	
	<div class = "mx-auto" style = "width : 75%;">
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{form|crispy}}
			{{form.media}}
			<button class = "btn btn-info" type = "submit">Güncelle</button>
		</form>
	</div>
    
{% endblock body %}